version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Running tests..."
      - pytest  # Run tests if applicable
      - echo "Building the project..."
      - python setup.py build  # Adjust based on EAIB structure

  post_build:
    commands:
      - echo "Deployment step..."
      - aws s3 cp eaib.zip s3://your-deployment-bucket/eaib.zip
      - echo "Build completed!"
